/**
 * Demo fixture data for Phase 10.5
 * 
 * Contains ~25 sample reservations for demo mode.
 * Dates are computed relative to "today" so data always looks alive.
 * IDs are stable/deterministic.
 */

// Helper to get date string relative to today
function relativeDate(daysFromToday: number): string {
    const d = new Date()
    d.setDate(d.getDate() + daysFromToday)
    return d.toISOString().split('T')[0]
}

// Helper to compute nights between dates
function nightsBetween(checkIn: string, checkOut: string): number {
    const a = new Date(checkIn)
    const b = new Date(checkOut)
    return Math.max(1, Math.round((b.getTime() - a.getTime()) / (1000 * 60 * 60 * 24)))
}

/**
 * Demo reservations fixture
 * Mix of confirmed, waiting, rejected, and finished stays
 * Returns any[] to avoid strict type requirements while still being useful
 */
export function getDemoReservations(): any[] {
    return [
        // ========== CONFIRMED - UPCOMING ==========
        {
            id: 'demo-001',
            guestName: 'Família Silva',
            phone: '+5516991234567',
            email: 'silva@email.com',
            partySize: 4,
            checkIn: relativeDate(2),
            checkOut: relativeDate(5),
            rooms: 2,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 180,
            breakfastPerPersonPerNight: 25,
            totalPrice: 1260,
            payment: {
                depositPaid: true,
                depositAmount: 630,
                events: [
                    { type: 'deposit', amount: 630, date: relativeDate(-5), note: 'Sinal pago via PIX' }
                ]
            },
            notesGuest: 'Chegada prevista às 14h',
            createdAt: relativeDate(-10),
            updatedAt: relativeDate(-5),
        },
        {
            id: 'demo-002',
            guestName: 'Carlos Mendes',
            phone: '+5516992345678',
            partySize: 2,
            checkIn: relativeDate(5),
            checkOut: relativeDate(7),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: false,
            nightlyRate: 150,
            breakfastPerPersonPerNight: 0,
            totalPrice: 300,
            payment: { depositPaid: false },
            createdAt: relativeDate(-3),
            updatedAt: relativeDate(-3),
        },
        {
            id: 'demo-003',
            guestName: 'Ana Paula Costa',
            phone: '+5516993456789',
            email: 'ana.costa@gmail.com',
            partySize: 3,
            checkIn: relativeDate(8),
            checkOut: relativeDate(10),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 160,
            breakfastPerPersonPerNight: 20,
            totalPrice: 440,
            payment: {
                depositPaid: true,
                depositAmount: 220,
                events: [
                    { type: 'deposit', amount: 220, date: relativeDate(-2), note: 'Depósito confirmado' }
                ]
            },
            createdAt: relativeDate(-7),
            updatedAt: relativeDate(-2),
        },
        {
            id: 'demo-004',
            guestName: 'Roberto Almeida',
            phone: '+5516994567890',
            partySize: 5,
            checkIn: relativeDate(12),
            checkOut: relativeDate(15),
            rooms: 2,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 200,
            breakfastPerPersonPerNight: 25,
            totalPrice: 975,
            payment: { depositPaid: false },
            notesInternal: 'Cliente frequente',
            createdAt: relativeDate(-5),
            updatedAt: relativeDate(-5),
        },
        {
            id: 'demo-005',
            guestName: 'Lucia Ferreira',
            phone: '+5516995678901',
            partySize: 2,
            checkIn: relativeDate(18),
            checkOut: relativeDate(20),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: false,
            nightlyRate: 140,
            breakfastPerPersonPerNight: 0,
            totalPrice: 280,
            payment: { depositPaid: false },
            createdAt: relativeDate(-2),
            updatedAt: relativeDate(-2),
        },

        // ========== WAITING ==========
        {
            id: 'demo-006',
            guestName: 'Marcos Oliveira',
            phone: '+5516996789012',
            email: 'marcos.oliveira@hotmail.com',
            partySize: 4,
            checkIn: relativeDate(3),
            checkOut: relativeDate(5),
            rooms: 2,
            status: 'waiting',
            breakfastIncluded: true,
            nightlyRate: 170,
            breakfastPerPersonPerNight: 22,
            totalPrice: 516,
            payment: { depositPaid: false },
            notesGuest: 'Aguardando confirmação de datas',
            createdAt: relativeDate(-1),
            updatedAt: relativeDate(-1),
        },
        {
            id: 'demo-007',
            guestName: 'Patricia Santos',
            phone: '+5516997890123',
            partySize: 2,
            checkIn: relativeDate(7),
            checkOut: relativeDate(9),
            rooms: 1,
            status: 'waiting',
            breakfastIncluded: false,
            nightlyRate: 150,
            breakfastPerPersonPerNight: 0,
            totalPrice: 300,
            payment: { depositPaid: false },
            createdAt: relativeDate(-1),
            updatedAt: relativeDate(-1),
        },
        {
            id: 'demo-008',
            guestName: 'Fernando Gomes',
            phone: '+5516998901234',
            partySize: 3,
            checkIn: relativeDate(10),
            checkOut: relativeDate(12),
            rooms: 1,
            status: 'waiting',
            breakfastIncluded: true,
            nightlyRate: 160,
            breakfastPerPersonPerNight: 20,
            totalPrice: 440,
            payment: { depositPaid: false },
            notesInternal: 'Primeiro contato via Instagram',
            createdAt: relativeDate(0),
            updatedAt: relativeDate(0),
        },

        // ========== REJECTED ==========
        {
            id: 'demo-009',
            guestName: 'Ricardo Pereira',
            phone: '+5516999012345',
            partySize: 6,
            checkIn: relativeDate(5),
            checkOut: relativeDate(8),
            rooms: 3,
            status: 'rejected',
            breakfastIncluded: true,
            nightlyRate: 180,
            breakfastPerPersonPerNight: 25,
            totalPrice: 990,
            payment: { depositPaid: false },
            notesInternal: 'Lotação máxima já atingida',
            createdAt: relativeDate(-3),
            updatedAt: relativeDate(-2),
        },
        {
            id: 'demo-010',
            guestName: 'Juliana Lima',
            phone: '+5516990123456',
            partySize: 2,
            checkIn: relativeDate(2),
            checkOut: relativeDate(4),
            rooms: 1,
            status: 'rejected',
            breakfastIncluded: false,
            nightlyRate: 150,
            breakfastPerPersonPerNight: 0,
            totalPrice: 300,
            payment: { depositPaid: false },
            notesInternal: 'Desistiu por conta própria',
            createdAt: relativeDate(-4),
            updatedAt: relativeDate(-3),
        },

        // ========== FINISHED (past dates, confirmed) ==========
        {
            id: 'demo-011',
            guestName: 'Eduardo Martins',
            phone: '+5516991111111',
            email: 'eduardo.m@email.com',
            partySize: 4,
            checkIn: relativeDate(-5),
            checkOut: relativeDate(-2),
            rooms: 2,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 180,
            breakfastPerPersonPerNight: 25,
            totalPrice: 840,
            payment: {
                depositPaid: true,
                depositAmount: 420,
                fullyPaid: true,
                events: [
                    { type: 'deposit', amount: 420, date: relativeDate(-10), note: 'Sinal' },
                    { type: 'final', amount: 420, date: relativeDate(-2), note: 'Acerto final' }
                ]
            },
            createdAt: relativeDate(-15),
            updatedAt: relativeDate(-2),
        },
        {
            id: 'demo-012',
            guestName: 'Camila Rodrigues',
            phone: '+5516992222222',
            partySize: 2,
            checkIn: relativeDate(-8),
            checkOut: relativeDate(-6),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: false,
            nightlyRate: 150,
            breakfastPerPersonPerNight: 0,
            totalPrice: 300,
            payment: { depositPaid: true, depositAmount: 150, fullyPaid: true },
            createdAt: relativeDate(-20),
            updatedAt: relativeDate(-6),
        },
        {
            id: 'demo-013',
            guestName: 'Bruno Souza',
            phone: '+5516993333333',
            partySize: 3,
            checkIn: relativeDate(-12),
            checkOut: relativeDate(-10),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 160,
            breakfastPerPersonPerNight: 20,
            totalPrice: 440,
            payment: { depositPaid: true, depositAmount: 220, fullyPaid: true },
            createdAt: relativeDate(-25),
            updatedAt: relativeDate(-10),
        },
        {
            id: 'demo-014',
            guestName: 'Renata Barbosa',
            phone: '+5516994444444',
            email: 'renata.b@gmail.com',
            partySize: 2,
            checkIn: relativeDate(-15),
            checkOut: relativeDate(-13),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: false,
            nightlyRate: 140,
            breakfastPerPersonPerNight: 0,
            totalPrice: 280,
            payment: { depositPaid: true, depositAmount: 140, fullyPaid: true },
            createdAt: relativeDate(-30),
            updatedAt: relativeDate(-13),
        },
        {
            id: 'demo-015',
            guestName: 'Gustavo Satler',
            phone: '+5516995555555',
            partySize: 5,
            checkIn: relativeDate(-20),
            checkOut: relativeDate(-17),
            rooms: 2,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 200,
            breakfastPerPersonPerNight: 25,
            totalPrice: 975,
            payment: { depositPaid: true, depositAmount: 487.5, fullyPaid: true },
            createdAt: relativeDate(-35),
            updatedAt: relativeDate(-17),
        },

        // ========== MORE UPCOMING FOR CALENDAR DENSITY ==========
        {
            id: 'demo-016',
            guestName: 'Thiago Nascimento',
            phone: '+5516996666666',
            partySize: 2,
            checkIn: relativeDate(3),
            checkOut: relativeDate(4),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: false,
            nightlyRate: 150,
            breakfastPerPersonPerNight: 0,
            totalPrice: 150,
            payment: { depositPaid: false },
            createdAt: relativeDate(-1),
            updatedAt: relativeDate(-1),
        },
        {
            id: 'demo-017',
            guestName: 'Mariana Dias',
            phone: '+5516997777777',
            partySize: 4,
            checkIn: relativeDate(5),
            checkOut: relativeDate(8),
            rooms: 2,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 175,
            breakfastPerPersonPerNight: 22,
            totalPrice: 789,
            payment: { depositPaid: true, depositAmount: 394.5 },
            createdAt: relativeDate(-4),
            updatedAt: relativeDate(-2),
        },
        {
            id: 'demo-018',
            guestName: 'Diego Castro',
            phone: '+5516998888888',
            partySize: 3,
            checkIn: relativeDate(6),
            checkOut: relativeDate(7),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 160,
            breakfastPerPersonPerNight: 20,
            totalPrice: 220,
            payment: { depositPaid: false },
            createdAt: relativeDate(-2),
            updatedAt: relativeDate(-2),
        },
        {
            id: 'demo-019',
            guestName: 'Vanessa Cardoso',
            phone: '+5516999999999',
            partySize: 2,
            checkIn: relativeDate(20),
            checkOut: relativeDate(23),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: false,
            nightlyRate: 145,
            breakfastPerPersonPerNight: 0,
            totalPrice: 435,
            payment: { depositPaid: false },
            notesGuest: 'Aniversário de casamento',
            createdAt: relativeDate(-1),
            updatedAt: relativeDate(-1),
        },
        {
            id: 'demo-020',
            guestName: 'André Moreira',
            phone: '+5516990000001',
            partySize: 6,
            checkIn: relativeDate(25),
            checkOut: relativeDate(28),
            rooms: 3,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 200,
            breakfastPerPersonPerNight: 25,
            totalPrice: 1050,
            payment: { depositPaid: true, depositAmount: 525 },
            notesInternal: 'Grupo grande, atenção especial',
            createdAt: relativeDate(-3),
            updatedAt: relativeDate(-1),
        },

        // ========== REPEAT CUSTOMERS (same phone) ==========
        {
            id: 'demo-021',
            guestName: 'Família Silva',
            phone: '+5516991234567',
            partySize: 3,
            checkIn: relativeDate(-30),
            checkOut: relativeDate(-28),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 170,
            breakfastPerPersonPerNight: 22,
            totalPrice: 472,
            payment: { depositPaid: true, depositAmount: 236, fullyPaid: true },
            createdAt: relativeDate(-45),
            updatedAt: relativeDate(-28),
        },
        {
            id: 'demo-022',
            guestName: 'Eduardo Martins',
            phone: '+5516991111111',
            partySize: 2,
            checkIn: relativeDate(-40),
            checkOut: relativeDate(-38),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: false,
            nightlyRate: 150,
            breakfastPerPersonPerNight: 0,
            totalPrice: 300,
            payment: { depositPaid: true, depositAmount: 150, fullyPaid: true },
            createdAt: relativeDate(-55),
            updatedAt: relativeDate(-38),
        },

        // ========== TODAY CHECK-IN/OUT ==========
        {
            id: 'demo-023',
            guestName: 'Paula Fonseca',
            phone: '+5516990000002',
            partySize: 2,
            checkIn: relativeDate(0),
            checkOut: relativeDate(2),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: true,
            nightlyRate: 160,
            breakfastPerPersonPerNight: 20,
            totalPrice: 400,
            payment: { depositPaid: true, depositAmount: 200 },
            notesGuest: 'Chegando hoje!',
            createdAt: relativeDate(-7),
            updatedAt: relativeDate(0),
        },
        {
            id: 'demo-024',
            guestName: 'Fabio Teixeira',
            phone: '+5516990000003',
            partySize: 3,
            checkIn: relativeDate(-2),
            checkOut: relativeDate(0),
            rooms: 1,
            status: 'confirmed',
            breakfastIncluded: false,
            nightlyRate: 150,
            breakfastPerPersonPerNight: 0,
            totalPrice: 300,
            payment: { depositPaid: true, depositAmount: 150 },
            notesInternal: 'Check-out hoje',
            createdAt: relativeDate(-10),
            updatedAt: relativeDate(0),
        },
    ]
}

// Export for API use
export const DEMO_RESERVATIONS = getDemoReservations()
